[tasks.default]
  links = [
    ["var/"],
    ["bin/"], # do I want this on all machines?
    [".vim/"],
    [".config/"],
    [".tmux.conf"], # do I want this on all machines?
    [".gitconfig"],
    [".githelpers"],
    [".cvsignore"],
    ["Library/Application Support/Karabiner/private.xml", "etc/Karabiner/private.xml"]
  ]
