[tasks.default]
  links = [
    ["var/"],
    ["bin/"],
    [".vim/"],
    [".config/nvim/", ".vim/"],
    [".config/nvim/init.vim", ".vim/vimrc"],
    [".config/"],
    [".tmux.conf"],
    [".gitconfig"],
    [".githelpers"],
    [".cvsignore"],
    ["Library/Application Support/Karabiner/private.xml", "etc/Karabiner/private.xml"]
  ]
  cmds = [
    ["bash", "Brewfile"],
    ["open", "--background", "-a", "/Applications/iTerm.app", "etc/iterm/Solarized_Dark-Patched.itermcolors"],
    ["open", "--background", "-a", "/Applications/iTerm.app", "etc/iterm/Solarized_Dark_Higher_Contrast.itermcolors"],
    ["open", "--background", "-a", "/Applications/iTerm.app", "etc/iterm/Solarized_Dark.itermcolors"],
    ["open", "--background", "-a", "/Applications/iTerm.app", "etc/iterm/Solarized_Light.itermcolors"]
  ]
