[tasks.default]
  links = [
    ["var/"],
    ["bin/"],
    [".vim/"],
    [".config/"],
    [".tmux.conf"],
    [".gitconfig"],
    [".githelpers"],
    [".cvsignore"],
    ["Library/Application Support/Karabiner/private.xml", "etc/Karabiner/private.xml"]
  ]
